// Code generated by protoc-gen-go.
// source: ProcessDefinition.proto
// DO NOT EDIT!

/*
Package com_npu_GarageDoor_proto is a generated protocol buffer package.

It is generated from these files:
	ProcessDefinition.proto

It has these top-level messages:
	ProcessDefinition
	ProcessDefItem
	ProcessDefResp
*/
package com_npu_GarageDoor_proto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 流程定义
type ProcessDefinition struct {
	// 模板名称
	IsTemplate       *bool             `protobuf:"varint,1,req" json:"IsTemplate,omitempty"`
	TempleteName     *string           `protobuf:"bytes,2,req" json:"TempleteName,omitempty"`
	DefItems         []*ProcessDefItem `protobuf:"bytes,3,rep" json:"DefItems,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProcessDefinition) Reset()         { *m = ProcessDefinition{} }
func (m *ProcessDefinition) String() string { return proto.CompactTextString(m) }
func (*ProcessDefinition) ProtoMessage()    {}

func (m *ProcessDefinition) GetIsTemplate() bool {
	if m != nil && m.IsTemplate != nil {
		return *m.IsTemplate
	}
	return false
}

func (m *ProcessDefinition) GetTempleteName() string {
	if m != nil && m.TempleteName != nil {
		return *m.TempleteName
	}
	return ""
}

func (m *ProcessDefinition) GetDefItems() []*ProcessDefItem {
	if m != nil {
		return m.DefItems
	}
	return nil
}

// 参数配置项
type ProcessDefItem struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	Value            *string `protobuf:"bytes,2,req" json:"Value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProcessDefItem) Reset()         { *m = ProcessDefItem{} }
func (m *ProcessDefItem) String() string { return proto.CompactTextString(m) }
func (*ProcessDefItem) ProtoMessage()    {}

func (m *ProcessDefItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProcessDefItem) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type ProcessDefResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	ErrorCode        *uint32 `protobuf:"varint,2,opt,name=error_code" json:"error_code,omitempty"`
	CameraId         *string `protobuf:"bytes,3,opt,name=camera_id" json:"camera_id,omitempty"`
	GarageId         *string `protobuf:"bytes,4,opt,name=garage_id" json:"garage_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProcessDefResp) Reset()         { *m = ProcessDefResp{} }
func (m *ProcessDefResp) String() string { return proto.CompactTextString(m) }
func (*ProcessDefResp) ProtoMessage()    {}

func (m *ProcessDefResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ProcessDefResp) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ProcessDefResp) GetCameraId() string {
	if m != nil && m.CameraId != nil {
		return *m.CameraId
	}
	return ""
}

func (m *ProcessDefResp) GetGarageId() string {
	if m != nil && m.GarageId != nil {
		return *m.GarageId
	}
	return ""
}

func init() {
}
