// EngineConstant
package constant

const (
	LOG_FILE_NAME = "enginelog.log"
	LOG_FILE_PATH = "log"

	CONFIG_RES_PATH  = "res"
	CONFIG_CONF_PATH = "conf"
	CONFIG_LOG_PATH  = "log"
	CONFIG_CFG_FILE  = "ProcessEngine.cfg.xml"
	TPC_PROC_ADD     = "p_addProc"
	TPC_PROC_LIST    = "p_ProcList"
	TPC_PROC_START   = "p_startProc"
	TPC_PROC_STOP    = "p_stopProc"
	TPC_PROC_DELETE  = "p_deleteProc"
	TPC_PROC_UPDATE  = ""
	TPC_PROC_OLEDIT  = "p_oleditProc"
	TPC_PROC_UPDQRY  = "p_oleditquery"
)
const (
	_ = iota
	CONFIG_LOGGER_FILEPATH
	// file type
	CONVERTER_FILE_TYPE_NIL
	CONVERTER_FILE_TYPE_XML
	CONVERTER_FILE_TYPE_JSON
	// deploy mode
	PROCENG_DEPLOY_MDOE_DEFAULT
	PROCENG_DEPLOY_MODE_UPDATE
	// deploy result
	PROCENG_DEPLOY_SUCCESS
	PROCENG_DEPLOY_FAILED
	PROCENG_DEPLOY_REPITITION
	// database execute result
	DB_EXEC_SUCCESS
	DB_EXEC_FAILED
	DB_EXEC_FAILED_RPT
	// node execute state
	EXECUTION_STATE_SUSPEND
	EXECUTION_STATE_EXECUTING
	// execution run const
	EXECUTION_RUN_STATE_INIT
	EXECUTION_RUN_STATE_EXECUTING
	EXECUTION_RUN_STATE_ERROR_STOP
	EXECUTION_RUN_STATE_DONE
	EXECUTION_FINISH_DONE
	EXECUTION_FINISH_PROC_END
	EXECUTION_FINISH_ERROR_STOP
	EXECUTION_FINISH_FORCE_STOP
	// msg type used to communicate between procInst and procExecution
	PROC_EXEC_MSG_TYPE_DONE
	PROC_EXEC_MSG_TYPE_END
	PROC_EXEC_MSG_TYPE_ADD
	PROC_EXEC_MSG_TYPE_FORCE_STOP
	// trans msg
	TRANS_RESULT_SUCCESS
	TRANS_RESULT_FAILED
)
