// Code generated by protoc-gen-go.
// source: ProcCmd.proto
// DO NOT EDIT!

/*
Package com_npu_garagedoor_phoneclient_proto is a generated protocol buffer package.

It is generated from these files:
	ProcCmd.proto

It has these top-level messages:
	ProcCmd
	ProcVariable
*/
package com_npu_garagedoor_phoneclient_proto

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProcCmd struct {
	// 执行命令的设备的id
	DeviceId *uint32 `protobuf:"varint,2,req,name=device_id" json:"device_id,omitempty"`
	// 操作码，
	OperationCode    *uint32         `protobuf:"varint,3,req,name=operation_code" json:"operation_code,omitempty"`
	HasReturn        *bool           `protobuf:"varint,7,opt,name=has_return,def=0" json:"has_return,omitempty"`
	HasParam         *bool           `protobuf:"varint,8,opt,name=has_param,def=0" json:"has_param,omitempty"`
	Params           []*ProcVariable `protobuf:"bytes,9,rep,name=params" json:"params,omitempty"`
	Returns          []*ProcVariable `protobuf:"bytes,10,rep,name=returns" json:"returns,omitempty"`
	Activity         *string         `protobuf:"bytes,12,opt,name=activity" json:"activity,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ProcCmd) Reset()         { *m = ProcCmd{} }
func (m *ProcCmd) String() string { return proto.CompactTextString(m) }
func (*ProcCmd) ProtoMessage()    {}

const Default_ProcCmd_HasReturn bool = false
const Default_ProcCmd_HasParam bool = false

func (m *ProcCmd) GetDeviceId() uint32 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

func (m *ProcCmd) GetOperationCode() uint32 {
	if m != nil && m.OperationCode != nil {
		return *m.OperationCode
	}
	return 0
}

func (m *ProcCmd) GetHasReturn() bool {
	if m != nil && m.HasReturn != nil {
		return *m.HasReturn
	}
	return Default_ProcCmd_HasReturn
}

func (m *ProcCmd) GetHasParam() bool {
	if m != nil && m.HasParam != nil {
		return *m.HasParam
	}
	return Default_ProcCmd_HasParam
}

func (m *ProcCmd) GetParams() []*ProcVariable {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ProcCmd) GetReturns() []*ProcVariable {
	if m != nil {
		return m.Returns
	}
	return nil
}

func (m *ProcCmd) GetActivity() string {
	if m != nil && m.Activity != nil {
		return *m.Activity
	}
	return ""
}

type ProcVariable struct {
	DataRef          *string `protobuf:"bytes,1,opt,name=data_ref" json:"data_ref,omitempty"`
	DataId           *string `protobuf:"bytes,2,opt,name=data_id" json:"data_id,omitempty"`
	DataType         *uint32 `protobuf:"varint,3,opt,name=data_type" json:"data_type,omitempty"`
	DataName         *string `protobuf:"bytes,4,opt,name=data_name" json:"data_name,omitempty"`
	DataValueStr     *string `protobuf:"bytes,5,opt,name=data_valueStr" json:"data_valueStr,omitempty"`
	DataValue        *uint32 `protobuf:"varint,6,opt,name=data_value" json:"data_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProcVariable) Reset()         { *m = ProcVariable{} }
func (m *ProcVariable) String() string { return proto.CompactTextString(m) }
func (*ProcVariable) ProtoMessage()    {}

func (m *ProcVariable) GetDataRef() string {
	if m != nil && m.DataRef != nil {
		return *m.DataRef
	}
	return ""
}

func (m *ProcVariable) GetDataId() string {
	if m != nil && m.DataId != nil {
		return *m.DataId
	}
	return ""
}

func (m *ProcVariable) GetDataType() uint32 {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return 0
}

func (m *ProcVariable) GetDataName() string {
	if m != nil && m.DataName != nil {
		return *m.DataName
	}
	return ""
}

func (m *ProcVariable) GetDataValueStr() string {
	if m != nil && m.DataValueStr != nil {
		return *m.DataValueStr
	}
	return ""
}

func (m *ProcVariable) GetDataValue() uint32 {
	if m != nil && m.DataValue != nil {
		return *m.DataValue
	}
	return 0
}

func init() {
}
