// Code generated by protoc-gen-go.
// source: Garage.proto
// DO NOT EDIT!

/*
Package Garage is a generated protocol buffer package.

It is generated from these files:
	Garage.proto

It has these top-level messages:
	Garage
	DsMessage
	DsParam
	JsonItem
	OpMap
*/
package Garage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Garage struct {
	InstanceId       *string `protobuf:"bytes,1,req,name=instance_id" json:"instance_id,omitempty"`
	DeviceId         *uint32 `protobuf:"varint,2,req,name=device_id" json:"device_id,omitempty"`
	Msgcmd           *uint32 `protobuf:"varint,3,req,name=msgcmd" json:"msgcmd,omitempty"`
	Content          []byte  `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Garage) Reset()         { *m = Garage{} }
func (m *Garage) String() string { return proto.CompactTextString(m) }
func (*Garage) ProtoMessage()    {}

func (m *Garage) GetInstanceId() string {
	if m != nil && m.InstanceId != nil {
		return *m.InstanceId
	}
	return ""
}

func (m *Garage) GetDeviceId() uint32 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

func (m *Garage) GetMsgcmd() uint32 {
	if m != nil && m.Msgcmd != nil {
		return *m.Msgcmd
	}
	return 0
}

func (m *Garage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type DsMessage struct {
	DeviceId         *uint32    `protobuf:"varint,1,req,name=device_id" json:"device_id,omitempty"`
	OperationId      *uint32    `protobuf:"varint,2,req,name=operation_id" json:"operation_id,omitempty"`
	HasParam         *bool      `protobuf:"varint,3,opt,name=has_param,def=0" json:"has_param,omitempty"`
	HasReturn        *bool      `protobuf:"varint,4,opt,name=has_return,def=0" json:"has_return,omitempty"`
	Params           []*DsParam `protobuf:"bytes,5,rep,name=params" json:"params,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DsMessage) Reset()         { *m = DsMessage{} }
func (m *DsMessage) String() string { return proto.CompactTextString(m) }
func (*DsMessage) ProtoMessage()    {}

const Default_DsMessage_HasParam bool = false
const Default_DsMessage_HasReturn bool = false

func (m *DsMessage) GetDeviceId() uint32 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

func (m *DsMessage) GetOperationId() uint32 {
	if m != nil && m.OperationId != nil {
		return *m.OperationId
	}
	return 0
}

func (m *DsMessage) GetHasParam() bool {
	if m != nil && m.HasParam != nil {
		return *m.HasParam
	}
	return Default_DsMessage_HasParam
}

func (m *DsMessage) GetHasReturn() bool {
	if m != nil && m.HasReturn != nil {
		return *m.HasReturn
	}
	return Default_DsMessage_HasReturn
}

func (m *DsMessage) GetParams() []*DsParam {
	if m != nil {
		return m.Params
	}
	return nil
}

type DsParam struct {
	Id               *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Datatype         *string `protobuf:"bytes,3,opt,name=datatype" json:"datatype,omitempty"`
	Value            *string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DsParam) Reset()         { *m = DsParam{} }
func (m *DsParam) String() string { return proto.CompactTextString(m) }
func (*DsParam) ProtoMessage()    {}

func (m *DsParam) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DsParam) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DsParam) GetDatatype() string {
	if m != nil && m.Datatype != nil {
		return *m.Datatype
	}
	return ""
}

func (m *DsParam) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type JsonItem struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JsonItem) Reset()         { *m = JsonItem{} }
func (m *JsonItem) String() string { return proto.CompactTextString(m) }
func (*JsonItem) ProtoMessage()    {}

func (m *JsonItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *JsonItem) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type OpMap struct {
	Values           []*JsonItem `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *OpMap) Reset()         { *m = OpMap{} }
func (m *OpMap) String() string { return proto.CompactTextString(m) }
func (*OpMap) ProtoMessage()    {}

func (m *OpMap) GetValues() []*JsonItem {
	if m != nil {
		return m.Values
	}
	return nil
}
